version: '3'
services:
  latest:
    build: ./python3.7
    image: tiangolo/python-machine-learning:latest
  python3.7:
    build: ./python3.7
    image: tiangolo/python-machine-learning:python3.7
  python3.6:
    build: ./python3.6
    image: tiangolo/python-machine-learning:python3.6
  cuda9.1-python3.7:
    build: ./cuda9.1-python3.7
    image: tiangolo/python-machine-learning:cuda9.1-python3.7
  cuda9.1-python3.6:
    build: ./cuda9.1-python3.6
    image: tiangolo/python-machine-learning:cuda9.1-python3.6
